import { Connection, PublicKey } from "@solana/web3.js";
import { Program, Provider, web3, BN } from "@project-serum/anchor";
import { IDL as PROGRAM_IDL } from "../target/types/battle";
import type { Battle } from "../target/types/battle";

/**
 * Returns the base IDL for the Battle program following as generated by Anchor with provided program ID appended to metadata.
 *
 * @param programId - Deployed program ID for the Battle program
 * @returns - The base IDL object
 */
export function getIDL(programId: web3.PublicKey): unknown {
  const _tmp = PROGRAM_IDL;
  _tmp["metadata"] = { address: programId.toBase58() };
  return _tmp;
}

/**
 * Get the Battle Anchor program
 * @param connection - the Solana connection object
 * @param programId - Deployed program ID for the Battle program
 * @returns the Battle anchor program
 */
export const getProgram = (
  connection: Connection,
  programId: web3.PublicKey
) => {
  const idl = getIDL(programId);
  const provider = new Provider(connection, null, null);
  const program = new Program(<Battle>idl, programId, provider);
  return program;
};
